### ISSUE TITLE
on dssSubscribe, hide the  My delivery and billing address are the same checkbox (TFS 35624)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/Advance-CPD-Merge#1]

**Comment by mkoza178** [comment]
Ready to test in Test env!

**Comment by beckywallace** [comment]
Check box has been removed per screen print below.  Can we have the highlighted text refer only to the Delivery Address?

![image](https://cloud.githubusercontent.com/assets/25667903/26495694/2bf300d0-41ea-11e7-9b4f-fa8964bc4a71.png)

**Comment by mkoza178** [comment]
Work item 35759 created

**Comment by LISAANN9266** [comment]
Also, the Please Confirm message also asks the customer to confirm the billing address.  Is that able to be modified in CMS?

**Comment by mkoza178** [comment]
Check in Test now.

**Comment by LISAANN9266** [comment]
Confirmed that "Billing & Delivery Information - Billing Address" has been changed to "Delivery Address"  

* Still need to confirm if we need or need to change the highlighted bar below - "Please confirm your billing and delivery address information before selecting submit to complete your subscription."

* Note:  TP shows 2 different phone numbers on the same page - see example.
![capture](https://cloud.githubusercontent.com/assets/25617462/26830581/263c49de-4a7e-11e7-82a0-cbf132af35d6.PNG)

**Comment by mkoza178** [comment]
TFS 35863 created to remove yellow banner.

**Comment by mkoza178** [comment]
The yellow banner is gone. Take a look in Test.

**Comment by beckywallace** [comment]
The banner is gone however when I enter all information, I get the message "please enter your billing last name" - all information has been completed:

![image](https://user-images.githubusercontent.com/25667903/27239781-edf9223c-5297-11e7-8250-50f0a48a04c7.png)


![image](https://user-images.githubusercontent.com/25667903/27239809-08fc6fd0-5298-11e7-85f8-04a9e27efd2a.png)

**Comment by mkoza178** [comment]
Good catch! Creating a work item.

**Comment by mkoza178** [comment]
TFS 35985

**Comment by mkoza178** [comment]
Resolved, test in the Test env.
