### ISSUE TITLE
Text prompts in payment fields (TFS 35760)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#10]
On dssSubscribe.aspx, there is text in the Name and Card Number fields (Cardholder Name, Card Number).  Can we get that same text in the Name and Card Number fields on Payment.aspx and EZPay.aspx?

dssSubscribe:
![image](https://cloud.githubusercontent.com/assets/25667903/26497867/a2154e6e-41f2-11e7-8a5e-58dfa2d00460.png)

**Comment by mkoza178** [comment]
Work item created.

**Comment by mkoza178** [comment]
Ready to test in Test env.

**Comment by beckywallace** [comment]
Confirmed.
