### ISSUE TITLE
Change Color from Blue to Orange behind view offers & activate account (TFS 35778)

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance-CPD-Merge#11]
Please change color to match color on nolas site. The blue behind the View Offers button and the blue Activate Account link. 
![coloronmemberpage](https://cloud.githubusercontent.com/assets/25616655/26505120/79ba88da-4215-11e7-9e99-6c00f603c196.png)

**Comment by mkoza178** [comment]
TFS created

**Comment by mkoza178** [comment]
Updated, ready to test.

**Comment by beckywallace** [comment]
![image](https://user-images.githubusercontent.com/25667903/29374514-457eea1e-8277-11e7-95af-3051605c7f67.png)
