### ISSUE TITLE
OPC - Activating Account - Enter Valid Email message

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance-CPD-Merge#12]
When trying to activate membership, I received a message to enter valid email, yet it showed that it was verified in the system.  Clicked on submit again (I know the email was correct) and I receive another message stating that the email already exists.  I was able to log in to the account with the new registered email as long as I went back to the beginning and just logged in.

![test4621056](https://cloud.githubusercontent.com/assets/25617462/26684310/737acc3e-469b-11e7-8862-51c67de73657.PNG)
![test2-421056](https://cloud.githubusercontent.com/assets/25617462/26684320/7905d270-469b-11e7-8094-48bffe38811f.PNG)
![test3-4621056](https://cloud.githubusercontent.com/assets/25617462/26684318/785cb028-469b-11e7-8fcb-2decd5e277ad.PNG)

**Comment by mkoza178** [comment]
Ready to test in Test env

**Comment by LISAANN9266** [comment]
No errors when testing.  Looks great.
