### ISSUE TITLE
Contrast for payment terms - payment.aspx (TFS 35877)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#13]
On other areas of the site (e.g. select an account to manage) when an area with black text is selected with a blue background, the text turns white which is a clean contrast.  On the payment.aspx page, the text is still black which makes the selected term difficult to read.  Can we either change the background color to something lighter, or have the text change to white?

Payment.aspx:
![image](https://user-images.githubusercontent.com/25667903/26895284-c4b3cbe2-4b86-11e7-940c-2af9000b5d3a.png)

SelectAccount.aspx - text for selection is white:
![image](https://user-images.githubusercontent.com/25667903/26895328-e360135c-4b86-11e7-91b7-56f03a8d4feb.png)

**Comment by mkoza178** [comment]
Work item created.

**Comment by mkoza178** [comment]
Ready to test

**Comment by LISAANN9266** [comment]
Looks good!

![capture](https://user-images.githubusercontent.com/25617462/27496172-cb31ecda-5809-11e7-8274-a48c089f4f14.PNG)
