### ISSUE TITLE
Text on payment page for stopped sub (TFS 35911)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#14]
When a stopped sub is on the payment.aspx page, the text "To make a payment, please select the amount you would like to pay" is not relevant.  This should either be removed or changed:

![image](https://user-images.githubusercontent.com/25667903/26942956-93033eac-4c49-11e7-8371-3f9593cfa3de.png)

**Comment by mkoza178** [comment]
Work item created

**Comment by mkoza178** [comment]
Ready to test in Test

**Comment by beckywallace** [comment]
Text has been removed.  Now receiving error to Select an amount to pay.  Separate GitHub opened on this (#17 - TFS 36738):

![image](https://user-images.githubusercontent.com/25667903/29374341-a53ccfee-8276-11e7-8c08-ad1e70d220bd.png)
