### ISSUE TITLE
Error on delivery issue, no log in SubCon

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#15]
Attempting to submit a complaint and receiving an error message however there is nothing in SubCon (Event Viewer or Event Processing Result) to indicate what the issue is:
![image](https://user-images.githubusercontent.com/25667903/27201884-f28e0bfe-51e4-11e7-8797-66c7ed5d7749.png)
![image](https://user-images.githubusercontent.com/25667903/27201909-09ac03c2-51e5-11e7-87a1-d28b5417077c.png)
![image](https://user-images.githubusercontent.com/25667903/27201921-221516e2-51e5-11e7-8d8a-ba043ddf2ea7.png)

**Comment by mkoza178** [comment]
Can you try again?

I was unable to reproduce when I tested this morning.

**Comment by beckywallace** [comment]
No issues today.
