### ISSUE TITLE
TFS 36737 MLIVE - Background / Foreground contrast

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#16]
The colors have changed on the test site (test-members.mlive.com) for selecting a publication that makes the publications close to unreadable.  Assuming this needs to stay the same as what is currently in production.

Test:
![image](https://user-images.githubusercontent.com/25667903/28982684-5bd39080-791c-11e7-8864-343de241db1b.png)

Production:
![image](https://user-images.githubusercontent.com/25667903/28982704-6ef4ee98-791c-11e7-8d54-f9ae2c8b1ecc.png)

**Comment by mkoza178** [comment]
Work item created for MG2 dev team.
