### ISSUE TITLE
CRITICAL - TFS 36738 Stopped sub payment error - Please select an amount to pay

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#17]
When a stopped subscriber is attempting to make a payment on the payment.aspx page, they are presented with an error "Please select an amount to pay".  This is incorrect because in this scenario, there is only one option to pay - the past due amount.

![image](https://user-images.githubusercontent.com/25667903/28983184-28af49c2-791e-11e7-9db0-652c050160d2.png)

**Comment by mkoza178** [comment]
Work item created.
