### ISSUE TITLE
CRITICAL - Delivery issues  - showing 13 of each (TFS 36809)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#18]
Each delivery issue is being shown 13 times in the "Select an Issue" field - appears to affect all papers:

![image](https://user-images.githubusercontent.com/25667903/29527034-2560f56c-865d-11e7-97d3-ddb0fce91182.png)

**Comment by mkoza178** [comment]
Work item created.

**Comment by mkoza178** [comment]
Looks resolved, check it out.
