### ISSUE TITLE
SYR - error on dssMatch.aspx (TFS 36810)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#20]
When trying to activate an account on dssMatch.aspx, receiving the following error.  Account is showing in Subscription Search as active and attempted transaction does not show in Event Processing Results:

**dssMatch:**
![image](https://user-images.githubusercontent.com/25667903/29529194-540ea394-8664-11e7-95a5-017b6b2a6e42.png)

**Subscription Search**
![image](https://user-images.githubusercontent.com/25667903/29529279-a5005a5e-8664-11e7-8d6f-5af7c366d027.png)

**Event Processing Result:**
![image](https://user-images.githubusercontent.com/25667903/29529216-6ea6a0ee-8664-11e7-924f-81e1d4969b02.png)

**Comment by mkoza178** [comment]
Work item created.

**Comment by beckywallace** [comment]
Appear to be getting this attempting to match for any paper.

**Comment by beckywallace** [comment]
@mkoza178 can we make this one a priority please?  Without being able to register accounts, especially for Cleveland, testing will be limited at best.

**Comment by mkoza178** [comment]
Can't reproduce. Let me know if you continue to run into it.
