### ISSUE TITLE
EasyPay Click Here text on Payment.aspx (TFS 36811)

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#21]
The highlighted text below for other pubs changes color when hovering over it.  Needs the same behavior for CLE - text should change to the same blue that is used for selected payment term when hovering over:

![image](https://user-images.githubusercontent.com/25667903/29530987-15da44cc-866c-11e7-9dc2-f78871e79792.png)

**Comment by mkoza178** [comment]
Work item created.

**Comment by mkoza178** [comment]
Ready for testing.
