### ISSUE TITLE
Wrong text on ChangePayment.aspx

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#22]
On ChangePayment.aspx, text is incorrect, states "to make a payment, lease select the amount you would like to pay".  This should be the same as is currently in production.  Screenshots of both below.

Test:
![image](https://user-images.githubusercontent.com/25667903/29839103-b5d98dfa-8cc2-11e7-83e7-15aa0fb7d1f2.png)

Production:
![image](https://user-images.githubusercontent.com/25667903/29839137-d3d93d3c-8cc2-11e7-9f5b-98ecad5fd710.png)

**Comment by mkoza178** [comment]
Updated in CMS. 
Clear cache and check it out.

**Comment by beckywallace** [comment]
![image](https://user-images.githubusercontent.com/25667903/29900349-f3ae6fe8-8db6-11e7-8c6e-439c304dce15.png)
