### ISSUE TITLE
CRITICAL - email notifications not being sent for Cleveland TFS 36834

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#23]
No email notifications are being sent for Cleveland - working for other pubs.

**Comment by mkoza178** [comment]
The team is working on and expects to have done shortly.

**Comment by mkoza178** [comment]
Ready to test.

**Comment by mkoza178** [comment]
I believe we confirmed this as well.

**Comment by beckywallace** [comment]
yes,
