### ISSUE TITLE
CRITICAL - Top of page graphic, menus missing from Cleveland test site

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#24]
Graphics and menus are missing from top of the test member site:

![image](https://user-images.githubusercontent.com/25667903/29871489-8dd54f12-8d51-11e7-96f5-c112df0b5558.png)

![image](https://user-images.githubusercontent.com/25667903/29871508-9fcb45dc-8d51-11e7-9624-bbcb86cc77ae.png)

**Comment by mkoza178** [comment]
This is due to us pointing CMS serv to copy of prod for deployment prep. We resolved this.
