### ISSUE TITLE
CRITICAL - Delivery issue (MISSED PAPER - NOLA) - nothing sent to system

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#26]
Delivery issue submitted with request for redelivery, nothing appears in SubCon:

![image](https://user-images.githubusercontent.com/25667903/29873734-f688e020-8d59-11e7-99ae-0917d1ee720b.png)

![image](https://user-images.githubusercontent.com/25667903/29873752-07d6f01a-8d5a-11e7-90b7-238413536fc1.png)

**Comment by mkoza178** [comment]
This is updated. It was due to our prep for the deployment. We pointed all transactions to a copy of prod database for testing.

We flipped back.
