### ISSUE TITLE
Wrong Codes for Delivery Issues TFS 36946

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#27]
Flowcharts show the following codes should be sent however every delivery issue I've done so far (prior day), only the code "CREDIT" is being sent.  See events 1034928 and 1034930

![image](https://user-images.githubusercontent.com/25667903/29899154-5ef12a78-8daf-11e7-9f51-20dba24a4491.png)

**Comment by mkoza178** [comment]
Work item created

**Comment by mkoza178** [comment]
Becky haven't had a chance to test myself, want to give a test in Test env?
