### ISSUE TITLE
No option to Credit account when delivery issue is within redelivery window TFS 36947

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#29]
Flowcharts show there should be three options when delivery issue is within redelivery window:  Redelivery, Credit, eEdition access.
![image](https://user-images.githubusercontent.com/25667903/29970206-4293e84e-8ee9-11e7-803d-176f314b316e.png)

When submitting a delivery issue within the redelivery window, only options presented are Redelivery and eEdition access:
![image](https://user-images.githubusercontent.com/25667903/29970190-2fbbfc0c-8ee9-11e7-9f00-a939c62bd5e0.png)

**Comment by mkoza178** [comment]
Work item created.

**Comment by beckywallace** [comment]
@mkoza178 the discussion on our call last week this is a non-issue.
