### ISSUE TITLE
CRITICAL - No email received for 3 - STARTSTD  TFS 36949 

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance-CPD-Merge#30]
Subscriber email notification not received for new start.  See configuration below:
![image](https://user-images.githubusercontent.com/25667903/29972682-90a8456c-8ef2-11e7-8abb-6cf25abf25c7.png)

**Comment by mkoza178** [comment]
Work item created

**Comment by mkoza178** [comment]
Becky, I believe we confirmed this yesterday, correct?

**Comment by beckywallace** [comment]
correct,
