### ISSUE TITLE
remove 'total amount' from paymentconfirm.aspx (TFS 35606)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/Advance-CPD-Merge#5]

**Comment by mkoza178** [comment]
Ready to test in Test env

**Comment by beckywallace** [comment]
Total Amount is still displayed:
![image](https://user-images.githubusercontent.com/25667903/26838030-9604e926-4aa4-11e7-82c2-4164dde773e4.png)

**Comment by beckywallace** [comment]
Disregard previous comment, I was on the wrong page - total amount has been removed from PaymentConfirm.aspx:

![image](https://user-images.githubusercontent.com/25667903/26838154-ee0b24d2-4aa4-11e7-890f-98f6bc97da4f.png)
