### ISSUE TITLE
 wrong CC type used in OPC (TFS 35724)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/Advance-CPD-Merge#6]

**Comment by mkoza178** [comment]
Ready to test in Test env

**Comment by mkoza178** [comment]
Test now.

**Comment by LISAANN9266** [comment]
OPC Test transaction for #893321 (This was a checking account - does this make a difference?)
![test893321](https://cloud.githubusercontent.com/assets/25617462/26683566/2219c6bc-4699-11e7-8332-a97a96dd2ff8.PNG)

**Comment by mkoza178** [comment]
Jason tested and confirmed.

**Comment by LISAANN9266** [comment]
Jason confirmed and test that it is now working correctly.
