### ISSUE TITLE
remove CVV from payment.aspx and ezpay.aspx (TFS 35619)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/Advance-CPD-Merge#8]

**Comment by mkoza178** [comment]
Ready to test in Test env

**Comment by beckywallace** [comment]
Verified:

![image](https://cloud.githubusercontent.com/assets/25667903/26497031/86b50cfc-41ef-11e7-8aba-449919a286d9.png)

![image](https://cloud.githubusercontent.com/assets/25667903/26497100/cb102c24-41ef-11e7-9e0a-4cdc0d7dce48.png)

![image](https://cloud.githubusercontent.com/assets/25667903/26497125/de9e23b8-41ef-11e7-8b8f-1569b50cde4a.png)
