### ISSUE TITLE
wrong notification presented on eBillsignup.aspx (TFS 35612)

### ISSUE THREAD

**Issue by mkoza178** [mkoza178/Advance-CPD-Merge#9]
Ready to test in Test env.

**Comment by beckywallace** [comment]
eBill signup email is not not being sent.

**Comment by beckywallace** [comment]
eBill signup email is still not being sent.  Verified it is being sent for other paper (NOLA), and set up of Event Type Email for Event 507 is identical between NOLA and Cleveland.  Received email for Nola but not for Plain Dealer

![image](https://user-images.githubusercontent.com/25667903/29691870-b0e83a68-88f2-11e7-97b6-abe247f303c2.png)
